[package]
name = "runc"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/opencontainers/runc/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/opencontainers/runc/releases/download/v1.1.5/runc.tar.xz"
path = "runc-v1.1.5.tar.xz"
sha512 = "7b10c0d6739e7fe3c718b3219bdb2437ae3ed8d1995b88136b9a0e8b4e909adbe8b6af6634a751b507bf793d0d5e924f5c85525d8fd46c3daf72c664dc25ab04"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
