[agent]
collection_jitter = "0s"
debug = false
flush_interval = "1s"
flush_jitter = "0s"
hostname = ""
interval = "60s"
logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
logtarget = "lumberjack"
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
quiet = false
round_interval = false

[inputs]

[[inputs.cpu]]
fieldpass = ["usage_idle", "usage_iowait", "usage_user", "usage_system"]
interval = "60s"
percpu = true
totalcpu = false
[inputs.cpu.tags]
metricPath = "metrics"

[[inputs.disk]]
fieldpass = ["used_percent", "inodes_free"]
interval = "60s"
tagexclude = ["mode"]
[inputs.disk.tags]
metricPath = "metrics"

[[inputs.diskio]]
fieldpass = ["io_time"]
interval = "60s"
[inputs.diskio.tags]
metricPath = "metrics"
report_deltas = "true"

[[inputs.mem]]
fieldpass = ["used_percent"]
interval = "60s"
[inputs.mem.tags]
metricPath = "metrics"

[[inputs.statsd]]
interval = "10s"
parse_data_dog_tags = true
service_address = ":8125"
[inputs.statsd.tags]
"aws:AggregationInterval" = "60s"
metricPath = "metrics"

[[inputs.swap]]
fieldpass = ["used_percent"]
interval = "60s"
[inputs.swap.tags]
metricPath = "metrics"

[outputs]

[[outputs.cloudwatch]]
force_flush_interval = "60s"
namespace = "CWAgent"
region = "us-east-1"
rollup_dimensions = [["InstanceId"]]
tagexclude = ["host", "metricPath"]
[outputs.cloudwatch.tagpass]
metricPath = ["metrics"]

[processors]

[[processors.delta]]

[[processors.ec2tagger]]
ec2_instance_tag_keys = ["bottlerocket-image"]
ec2_metadata_tags = ["ImageId", "InstanceId", "InstanceType"]
refresh_interval_seconds = "0s"
[processors.ec2tagger.tagpass]
metricPath = ["metrics"]