version = {{version}}

# Basic vlan dhcp
[vlan2]
kind = "VLAN"
device = "eno1"
id = 2
dhcp4 = true

[vlan3]
kind = "Vlan"
device = "eno2"
id = 3
dhcp6 = true

# Static4
[vlan4]
kind = "vlan"
device = "eno3"
id = 4

[vlan4.static4]
addresses = ["10.0.0.9/24"]

# two devices on same vlan
[firstvlan10]
kind = "vlan"
device = "eno4"
id = 10
dhcp4 = true

[secondvlan10]
kind = "vlan"
device = "eno5"
id = 10
dhcp4 = true
